= Installing Awesome Procedures (apoc)
:author: Neo4j Engineering

== APOC library installation

https://twitter.com/mesirii[Michael Hunger] has created the
https://github.com/neo4j-contrib/neo4j-apoc-procedures[apoc] library which contains lots of useful procedures that we can use in our Neo4j applications.

Let’s get `apoc` installed on our local instances of Neo4j:

* You should have already copied `apoc.jar` onto your machine. If you haven’t, then grab a USB stick from one of the trainers or download the latest version of apoc from https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/latest
* Copy `apoc.jar` into your `plugins` folder wherever you have installed Neo4j.
* Restart Neo4j

== Check apoc installed correctly

If you run the following command, you can see which additional procedures are now available to us:

[source,highlight,pre-scrollable,programlisting,cm-s-neo,code,runnable,standalone-example,ng-binding]
----
CALL dbms.procedures()
YIELD name, signature
WITH name, signature
WHERE name STARTS WITH "apoc"
RETURN name, signature
----

If you don’t see any rows, grab your closest trainer for help. 
Once you’ve got it installed, you can close this guide and return to the previous one.